name: CI Test

on:
  push:
    branches: [ "master" ]
###########################################

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        host: ${{secrets.HOST}}
        passwrod : ubuntu
        username : ubuntu
        port : ${{secrets.REMOTE_SSH_PORT}}
        script: | 
          echo "test" > "FILENAME"
      
