name: CI Test

on:
  push:
    branches: [ "master" ]
###########################################

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        host: ${{secrets.HOST}}
        passwrod : ubuntu
        username : ubuntu
        port : ${{secrets.REMOTE_SSH_PORT}}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: | 
          cd /home/ubuntu
          sudo echo "test" > "FILENAME"
      
