name: CI Test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: SSH 연결 설정
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.KEY }}

    - name: 원격 서버로 파일 전송 및 실행
        host:${{ secrets.HOST }}
        port:${{ secrets.REMOTE_SSH_PORT }}
        username:ubuntu
        script:|
        cd /home/ubuntu && echo "test" > FILENAME
