name: CI Test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: SSH 연결 설정4
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.KEY }}
        username: ununtu

    - name: 원격 서버로 파일 전송 및 실행
      run: |
        ssh ubuntu@${{ secrets.HOST }} -p ${{ secrets.REMOTE_SSH_PORT }} 'cd /home/ubuntu && echo "test" > FILENAME'
